name: BooDev
main: com.jskingboo.boodev.Main
version: 0.4.2
authors:
  - JsKingBoo
description: Map dev plugin that's better than Elevation
commands:
  gm:
    description: Toggle between creative and survival
    usage: /gm
  enchant:
    description: Almost unrestrained enchanting
    usage: /enchant <enchantment ID> <enchantment level>
  name:
    description: Renames item
    usage: /name <name>
  lore:
    description: Add a line of lore to an item
    usage: /lore <line>
  jumpto:
    description: Jump to block being pointed to
    usage: /jumpto
  slap:
    description: Slap a person
    usage: /slap <player>
  rocket:
    description: Send someone flying upwards!
    usage: /rocket <player>
  halt:
    description: Stop someone in his/her tracks
    usage: /halt <player>
  hook:
    description: Hook someone towards you
    usage: /hook <player>
  brush:
    description: Get a brush
    usage: /brush <sphere/cube> <radius> <block>